'use strict';

//
// This file is @AUTOGENERATED
//

module.exports = function(grunt) {
    grunt.initConfig({
    "test": {
        "target": {
            "do": "something",
            "random": 647023066
        }
    },
    "test2": {
        "target1": {
            "do": "something too",
            "time": 1443128650
        },
        "target2": {
            "do": "even more",
            "unique": "5604654a64461"
        }
    }
});

    // imports
    grunt.loadNpmTasks('import1');
    grunt.loadNpmTasks('import2');
    grunt.loadNpmTasks('import5604654a64461');

    // tasks
    grunt.registerTask('testTask', ["test:target","test2:target1","test2:target2"]);
    grunt.registerTask('randomTask', ["random:_5604654a64461"]);
};
